//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gurdian_picture_tool.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.0.3.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"NTQyNjM3QDMxMzkyZTMzMmUzMEM3L1FZWW1rZ2NPdy9hNlNuWUFmZFNiV1hSRXZEZjlCUFkycWVqdkMwMkk9;NTQyNjM4QDMxMzkyZTMzMmUzMG9NZi9XYWVvd052WW1uMFFjWkNXR3paZ2pXUnl3NlVwZUhHQzJRc0VzbkE9;NTQyNjM5QDMxMzkyZTMzMmUzMG5aWFhsV25YS0ZpVnJYeUFQZUZKMmEvN2lvUkQvQ1YyVGZ0WEl4SHd6QWc9;NTQyNjQwQDMxMzkyZTMzMmUzMGpPUExNOGlXVjJuYzhyNGUzME5sQ3R0VHFZa2k5RjNBeXRGZjV3MG1QZnc9;NTQyNjQxQDMxMzkyZTMzMmUzME1Xd3lMTWQ2VERibHNDRXdMa2VXQ0N5bTBxK2h6R2k0NFNwZ0twaHRNQ3c9;NTQyNjQyQDMxMzkyZTMzMmUzMEorMDlOdzkxRHBrN0lEaXlmTXp4bjl1elhDUzkydWIyejgxSTJFRzNtZzg9;NTQyNjQzQDMxMzkyZTMzMmUzMGZXOVFwSnR0VGpuVzFEWTNxM0hRVmh6YWYyb3p3MFdiZng2S1lRZ1hyY289;NTQyNjQ0QDMxMzkyZTMzMmUzMGpLS0FuZEEwUUpiOEpqTEtIcUVBVmtqM08rVU80Zng5N2dtNk5UTXNNUjQ9;NTQyNjQ1QDMxMzkyZTMzMmUzME5DdFBocFU2NUw0WXJDenFSMGR1elhSaHZWRWdSK3RuZFh1VFVkTEJkTkk9;NTQyNjQ2QDMxMzkyZTMzMmUzMFFBT0tXVmRJNDBwYmRTQ3dwSVErcUZvQWZsQ01NRTFDKzYxU0dUVmVJOXc9;NTQyNjQ3QDMxMzkyZTMzMmUzMEh6aGFBVGZuTlh2TkNXTEZxSGNJRFczeE1sZmZyRE9LcldwU0p2aHF6WGs9")]
        public string SfFormKey {
            get {
                return ((string)(this["SfFormKey"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public string r {
            get {
                return ((string)(this["r"]));
            }
            set {
                this["r"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public string g {
            get {
                return ((string)(this["g"]));
            }
            set {
                this["g"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public string b {
            get {
                return ((string)(this["b"]));
            }
            set {
                this["b"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("250")]
        public int pngQualityInKB {
            get {
                return ((int)(this["pngQualityInKB"]));
            }
            set {
                this["pngQualityInKB"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("80")]
        public string jpgQuality {
            get {
                return ((string)(this["jpgQuality"]));
            }
            set {
                this["jpgQuality"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("jpg")]
        public string format {
            get {
                return ((string)(this["format"]));
            }
            set {
                this["format"] = value;
            }
        }
    }
}
